### ISSUE TITLE
[FilterableListpicker] App crash when using FilterableListpicker

### ISSUE THREAD

**Issue by kefahB** [nstudio/nativescript-plugins#105]
Hi @davecoffin,

I am facing an app crash when using filterable-list-picker with this error .. I didn't declare any visibility property! 

It seams like some think wired with the NS ! I don't see any think wrong with the plugin!

```ts
  NativeScript encountered a fatal error: Uncaught Error: Invalid visibility value: FilterableListpicker<myfilter>@phoneNumber/phone-number-page.xml:38:5;. Valid values are: "visible", "hidden", "collapse".

```

**Comment by davecoffin** [comment]
I'm not seeing that crash in any of my apps, can you share more code?

**Comment by kefahB** [comment]
Hi @davecoffin,

Sorry about the delay, I didi not think special, the plugin worked fine, until a point that the crash appear! I use the latest NS version...


```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
xmlns:ui="@nstudio/nativescript-filterable-listpicker"
navigatingTo="navigatingTo" class="page">
    <Page.actionBar>
	    <ActionBar title="{{L('my_car')}}" icon="" class="action-bar">
		</ActionBar>
	</Page.actionBar>
    
    <GridLayout>
        
        <ui:FilterableListpicker focusOnShow="false" id="myfilter" blur="dark" dimmerColor="rgba(76,196,211,0.7)"  hintText="Type to filter..." source="{{listitems}}" canceled="{{cancelFilterableList}}" itemTapped="{{itemTapped}}" />        

    </GridLayout>
</Page>
```

IOS crash stack
```ts
Binding: TypeError: value1.equals is not a function at Label(16)
  Binding: TypeError: value1.equals is not a function at TextField<filterTextField>
  Binding: TypeError: value1.equals is not a function at StackLayout(20)
  ***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error: Uncaught Error: -[ArrayAdapter _isDynamic]: unrecognized selector sent to instance 0x600002bf7cf0
  at
  _setColor(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/text-base/index.ios.js:224:0)
  at [color:setNative](file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/text-base/index.ios.js:151:0)
  at applyAllNativeSetters(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/properties/index.js:1152:0)
  at initNativeView(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/properties/index.js:1079:0)
  at onResumeNativeUpdates(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:739:22)
  at _resumeNativeUpdates(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:280:0)
  at onLoaded(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:235:0)
  at onLoaded(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view/view-common.js:107:0)
  at (file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:318:0)
  at callFunctionWithSuper(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:312:0)
  at callLoaded(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:318:0)
  at loadView(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:458:0)
  at (file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:237:0)
  at eachChildView(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
  at eachChild(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view/view-common.js:772:0)
  at onLoaded(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:236:0)
  at onLoaded(file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view/view-common.js:107:0)
  at (file: app/webpack:/cocarz/node_modules/@nativescript/core/ui/core/view-base/index.js:318:0)
  at callFunction<…>
```

Android
```ts
JS: Binding: TypeError: value1.equals is not a function at Label(16)
  JS: Binding: TypeError: value1.equals is not a function at TextField<filterTextField>
  JS: Binding: TypeError: value1.equals is not a function at StackLayout(20)
  System.err: An uncaught Exception occurred on "main" thread.
  System.err: Unable to resume activity {com.cocarz/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreateView failed
  System.err: Error: Cannot convert object to Landroid/content/res/ColorStateList; at index 0
  System.err:
  System.err: StackTrace:
  System.err: java.lang.RuntimeException: Unable to resume activity {com.cocarz/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreateView failed
  System.err: Error: Cannot convert object to Landroid/content/res/ColorStateList; at index 0
  System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4803)
  System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4836)
  System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
  System.err: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
  System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
  System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
  System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
  System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
  System.err: 	at android.os.Looper.loop(Looper.java:288)
  System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
  System.err: 	at java.lang.reflect.Method.invoke(Native Method)
  System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
  System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreateView failed
  System.err: Error: Cannot convert object to Landroid/content/res/ColorStateList; at index 0
  System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
  System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
  System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
  System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
  System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
  System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
  System.err: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
  System.err: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
  System.err: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
  System.err: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
  System.err: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
  System.err: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
  System.err: 	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:495)
  System.err: 	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:312)
  System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1531)
  System.err: 	at android.app.Activity.performResume(Activity.java:8422)
  System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4793)
  System.err: 	... 13 more
```

**Comment by davecoffin** [comment]
Hm seems like it could be a styling problem, try pasting the CSS in the readme and see if that solves it.

**Comment by kefahB** [comment]
I already did .. still same think

**Comment by davecoffin** [comment]
It seems like a problem with color not being set. I'm not seeing this in my apps, not sure whats different. Can you reproduce on the demo? Try simply adding this:

.flp-container .flp-list-container {
  color: #333; // or whatever color you want
  border-radius: 10;
}

**Comment by kefahB** [comment]
With a brand new project it work ! What do you think I have in my project that causing the crash !?

**Comment by davecoffin** [comment]
I've seen this error before, not on this plugin but it is definitely due to a color not being set on a UI element. I'm not under what conditions it crops up. Did you try the css i recommended above?

**Comment by kefahB** [comment]
Yes I did .. maybe it is related to the them it self !

**Comment by kefahB** [comment]
Hi @davecoffin, I got the error, it is strange, but I had created a filter to bind the color like this `color="{{ color('dark') }}` and this causing the error because `value2` it is the `color` function that I've created at [this line](https://github.com/NativeScript/NativeScript/blob/47231145acb851552d7990e5a75b66dd6d06fee8/packages/core/color/color-common.ts#L150)

But why the plugin crash and only this plugin I don't know !! the filter worked just fine!


```ts
export const color = (color: string) => {
    let c;
    switch (color) {
        case 'blue':
            c = cczBlue;
            break;
        case 'green':
            c = cczGreen;
            break;
        case 'ornage':
            c = cczOrange;
            break;
        case 'muted':
            c = muted;
            break;
        case 'dark':
            c = dark;
            break;
    }
    return c;
}
```

```ts
>> ===================
 value1 #262626
  value2 function color(color) {
  let c;
  switch (color) {
  case 'blue':
  c = _functions__WEBPAC...<omitted>...
  }
<< ==================
>> ==================
  value1 function color(color) {
  let c;
  switch (color) {
  case 'blue':
  c = _functions__WEBPAC...<omitted>...
  }
  value2 function color(color) {
  let c;
  switch (color) {
  case 'blue':
  c = _functions__WEBPAC...<omitted>...
  }
<< ================

```

**Comment by kefahB** [comment]
Ah,

When I set the full css it crash .. but setting your suggestion it work !

```ts
// this work
.flp-container .flp-list-container {
color: #333; // or whatever color you want
border-radius: 10;
}
```

**Comment by davecoffin** [comment]
Yea weird. I've seen it before. My css simply explicitly set the color, and that's what fixes it for some reason. Glad you got through it!

**Comment by kefahB** [comment]
oh dear I've found the real issue !! I setting a global resources filter called `color` this causing a lot of problems ! rename this resource resolve the issue completely. for future use :D
