### ISSUE TITLE
@nstudio/nativescript-filterable-listpicker not working with NS 8

### ISSUE THREAD

**Issue by jcassidyav** [nstudio/nativescript-plugins#48]
When using with NS 8 I get an error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: Parsing XML at 2:11
System.err:  > Module 'GridLayout' not found for element 'GridLayout'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "@nativescript/core/ui", relative to: app/tns_modules/
System.err:
System.err: StackTrace:
System.err: ScopeError(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\utils\debug.js:51:0)
System.err:     at PositionErrorFormat(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\builder\index.js:222:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\builder\index.js:207:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\xml\index.js:412:0)
System.err:     at EasySAXParser.parse(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\js-libs\easysax\easysax.js:751:0)
System.err:     at parse(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\xml\index.js:455:0)
System.err:     at parse(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\builder\index.js:213:0)
System.err:     at parseInternal(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\builder\index.js:181:0)
System.err:     at parse(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\builder\index.js:49:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nstudio\nativescript-filterable-listpicker\common.js:72:29)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\content-view\index.js:65:0)
System.err:     at eachChildView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\page\page-common.js:106:0)
System.err:     at eachChild(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at onLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\page\index.android.js:38:0)
System.err:     at (file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at _addViewCore(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:453:0)
System.err:     at _addView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\core\view-base\index.js:439:0)
System.err:     at onCreateView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\frame\index.android.js:739:0)
System.err:     at onCreateView(file: src\webpack:\@nativescript\template-hello-world-ng\node_modules\@nativescript\core\ui\frame\fragment.android.js:25:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
System.err:     at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I've attached a sample app, created with ```ns create``` choosing angular & then adding the plugin.

[angular.zip](https://github.com/nstudio/nativescript-plugins/files/6501329/angular.zip)

**Comment by NathanWalker** [comment]
Thanks for the repro here @jcassidyav

**Comment by rigor789** [comment]
A temporary fix is to add 
```ts
require('@nativescript/core/bundle-entry-points');
```

at the top of `main.ts` - we'll be adding that line by default in the base webpack configs soon, since the original assumption that XMLBuilder would only be used in ts/js flavors is incorrect, because plugins (like this one) can technically use the XMLBuilder regardless of the application flavor.

**Comment by jcassidyav** [comment]
That's great thanks, work around working for me.

**Comment by comporell** [comment]
> 
> 
> A temporary fix is to add
> 
> ```ts
> require('@nativescript/core/bundle-entry-points');
> ```
> 
> at the top of `main.ts` - we'll be adding that line by default in the base webpack configs soon, since the original assumption that XMLBuilder would only be used in ts/js flavors is incorrect, because plugins (like this one) can technically use the XMLBuilder regardless of the application flavor.

Dear rigor789 I've been trying to find a fix for a similar issue since days! I had this issue on another plugin and this line above fixed my project. Thank you so much! When do you think it will be added to webpack?
